### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by Julietnj** [NetManAIOps/PSqueeze#1]
你好，请问PSqueeze代码是否有License? 是否可以修改和使用其中的代码？谢谢

**Comment by lizeyan** [comment]
我们添加了MIT license，所有人都可以任意使用、分发、修改这份代码，但是我们不负任何责任。
<img width="695" alt="image" src="https://user-images.githubusercontent.com/12494243/174738437-b67430c2-d144-4d88-aebe-0f0343d75654.png">
#2

**Comment by Julietnj** [comment]
谢谢答复
