### ISSUE TITLE
网盘链接不存在

### ISSUE THREAD

**Issue by zhanpengjie** [NetManAIOps/PSqueeze#3]
您好数据集的网盘链接不存在，可以麻烦再发一份吗

**Comment by lizeyan** [comment]
我得找时间再找找这个数据。应该是因为毕业了，学校直接把我的网盘账号给关了。

**Comment by JasonPeng1310** [comment]
这个数据集获取不了 All datasets are available at Tsinghua Cloud: https://cloud.tsinghua.edu.cn/d/aa4102a5d1614e57bc36/

**Comment by lizeyan** [comment]
https://zenodo.org/record/8153849
